spring:
  application:
    name: FOOD-CATALOG-SERVICE
  datasource:
    username: root
    password: KrishnaRekha
    url: jdbc:mysql://localhost:3306/employee_management_system?userSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update